Import the numpy module

In [13]:
import numpy as np

Create a 1d numpy array called arr1 that looks like the one below. Display it.

In [14]:
list1 = [3, 6, 9, 12, 15]
arr1 = np.array(list1)
arr1

array([ 3,  6,  9, 12, 15])

Print out the 3rd element of the array.

In [15]:
arr1[2]

9

Create a 2d numpy array called arr2 that looks like the one below. Display it.

In [16]:
list2 = [[2, 4, 6], [3, 6, 9], [4, 8, 12]]
arr2 = np.array(list2)
arr2

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

Print out the element at row index=2, col index=1.

In [17]:
arr2[2,1]

8

Create an array that goes from 0 to 100 with step=3. Display it.

In [18]:
np.arange(start=0, stop=100, step=3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Create a 10x5 2d array filled with zeroes. Display it.

In [19]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create an array called lin1d, that has 100 data points spaced between 57 and 108. Display it.

In [20]:
lin1d = np.linspace(start=57, stop=108, num=100)
lin1d

array([ 57.        ,  57.51515152,  58.03030303,  58.54545455,
        59.06060606,  59.57575758,  60.09090909,  60.60606061,
        61.12121212,  61.63636364,  62.15151515,  62.66666667,
        63.18181818,  63.6969697 ,  64.21212121,  64.72727273,
        65.24242424,  65.75757576,  66.27272727,  66.78787879,
        67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
        69.36363636,  69.87878788,  70.39393939,  70.90909091,
        71.42424242,  71.93939394,  72.45454545,  72.96969697,
        73.48484848,  74.        ,  74.51515152,  75.03030303,
        75.54545455,  76.06060606,  76.57575758,  77.09090909,
        77.60606061,  78.12121212,  78.63636364,  79.15151515,
        79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
        81.72727273,  82.24242424,  82.75757576,  83.27272727,
        83.78787879,  84.3030303 ,  84.81818182,  85.33333333,
        85.84848485,  86.36363636,  86.87878788,  87.39393939,
        87.90909091,  88.42424242,  88.93939394,  89.45

Reshape lin1d to be 10x10 and call it lin2d. Display it.

In [30]:
lin2d = lin1d.reshape(10,10)
lin2d

array([[ 57.        ,  57.51515152,  58.03030303,  58.54545455,
         59.06060606,  59.57575758,  60.09090909,  60.60606061,
         61.12121212,  61.63636364],
       [ 62.15151515,  62.66666667,  63.18181818,  63.6969697 ,
         64.21212121,  64.72727273,  65.24242424,  65.75757576,
         66.27272727,  66.78787879],
       [ 67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
         69.36363636,  69.87878788,  70.39393939,  70.90909091,
         71.42424242,  71.93939394],
       [ 72.45454545,  72.96969697,  73.48484848,  74.        ,
         74.51515152,  75.03030303,  75.54545455,  76.06060606,
         76.57575758,  77.09090909],
       [ 77.60606061,  78.12121212,  78.63636364,  79.15151515,
         79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
         81.72727273,  82.24242424],
       [ 82.75757576,  83.27272727,  83.78787879,  84.3030303 ,
         84.81818182,  85.33333333,  85.84848485,  86.36363636,
         86.87878788,  87.39393939],
       [ 8

Print out the shape of lin1d and lin2d.

In [22]:
print("lin1d:", lin1d.shape)
print("lin2d:", lin2d.shape)

lin1d: (100,)
lin2d: (10, 10)


Generate a 5x5 array of random numbers called nums. Display it.

In [23]:
nums = np.random.rand(5,5)
nums

array([[0.64517717, 0.6777465 , 0.77972566, 0.6006764 , 0.19146619],
       [0.84952113, 0.30661651, 0.94454836, 0.62590516, 0.33354171],
       [0.77438488, 0.07866406, 0.75203167, 0.25204271, 0.77129297],
       [0.2910817 , 0.32820439, 0.24923474, 0.13210626, 0.46791753],
       [0.57930079, 0.53379116, 0.57096518, 0.60852422, 0.35592309]])

Print out the min, max and mean of the nums array.

In [24]:
print("Min:", nums.min())
print("Max:", nums.max())
print("Mean:", nums.mean())

Min: 0.07866406165705386
Max: 0.9445483583601585
Mean: 0.5080156054144396


Multiple the entire array nums x2 and store it back in nums. Display the result.

In [25]:
nums = nums * 2
nums

array([[1.29035433, 1.355493  , 1.55945132, 1.2013528 , 0.38293239],
       [1.69904227, 0.61323302, 1.88909672, 1.25181031, 0.66708343],
       [1.54876976, 0.15732812, 1.50406335, 0.50408543, 1.54258593],
       [0.5821634 , 0.65640878, 0.49846949, 0.26421253, 0.93583505],
       [1.15860157, 1.06758232, 1.14193035, 1.21704844, 0.71184618]])

Select row index 1 to 2 and col index 2 to 3 and display the result.

In [26]:
nums[1:3, 2:4]

array([[1.88909672, 1.25181031],
       [1.50406335, 0.50408543]])

Modify that same selection by multiplying it x10, then display the new nums array.

In [27]:
nums[1:3, 2:4] = nums[1:3, 2:4] * 10
nums

array([[ 1.29035433,  1.355493  ,  1.55945132,  1.2013528 ,  0.38293239],
       [ 1.69904227,  0.61323302, 18.89096717, 12.51810312,  0.66708343],
       [ 1.54876976,  0.15732812, 15.04063349,  5.04085426,  1.54258593],
       [ 0.5821634 ,  0.65640878,  0.49846949,  0.26421253,  0.93583505],
       [ 1.15860157,  1.06758232,  1.14193035,  1.21704844,  0.71184618]])